# Generated by Django 5.2.5 on 2025-10-01 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import midas.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, null=True)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=midas.models.Scanner.generate_scanner_id,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subteam',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedTag',
            fields=[
                ('code', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'tag',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='midas.claimedtag',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'starting_from',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'quota',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='midas.quota'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PendingTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, null=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'scanner',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='midas.scanner'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'checkin',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkin_session',
                        to='midas.log',
                    ),
                ),
                (
                    'checkout',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkout_session',
                        to='midas.log',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SubteamMembership',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'period',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='midas.assignment',
                    ),
                ),
                (
                    'subteam_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='midas.subteam'
                    ),
                ),
            ],
        ),
    ]
