# Generated by Django 5.2.5 on 2025-10-01 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('midas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='session',
            name='checkout',
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'session',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkin',
                        to='midas.session',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='midas.claimedtag',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.CharField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'session',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkout',
                        to='midas.session',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='midas.claimedtag',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
