# Generated by Django 5.2.5 on 2025-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('midas', '0002_remove_session_checkin_remove_session_checkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='subteams',
            field=models.ManyToManyField(to='midas.subteam'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='type',
            field=models.CharField(choices=[('tag', 'tag scan'), ('remote', 'remote')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='type',
            field=models.CharField(choices=[('tag', 'tag scan'), ('remote', 'remote')]),
        ),
        migrations.DeleteModel(
            name='SubteamMembership',
        ),
    ]
