# Generated by Django 5.2.5 on 2025-10-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('midas', '0003_rename_owner_session_user_assignment_subteams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checkins',
                to='midas.claimedtag',
            ),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checkouts',
                to='midas.claimedtag',
            ),
        ),
        migrations.AlterField(
            model_name='claimedtag',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='claimed_tags',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='pendingtag',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pending_tags',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='pendingtag',
            name='scanner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pending_tag',
                to='midas.scanner',
            ),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
