# Generated by Django 5.2.5 on 2025-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('midas', '0004_alter_assignment_user_alter_checkin_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
