# Generated by Django 5.2.5 on 2025-10-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('midas', '0005_alter_quota_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='quota',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='midas.quota'
            ),
        ),
        migrations.AlterField(
            model_name='pendingtag',
            name='scanner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='pending_tag',
                to='midas.scanner',
            ),
        ),
    ]
