services:
  serve:
    image: roboteamtwente/rfid-tracker-serve@sha256:42759e6bb88812ae3d453c872d73cbfdf2c2dc2e1b2afe800fd8436fd1b917b2
    ports:
      - 8001:8000
    volumes:
      - db:/db
      - ./credentials:/credentials
    environment:
      - DATABASE_URL=sqlite:///db/db.sqlite3
      - DJANGO_BACKUP_CREDENTIALS_FILE=/credentials/service-account.json
      - DJANGO_BACKUP_SHARED_DRIVE_ID=REPLACE_ME
      - DJANGO_BACKUP_FOLDER_NAME=REPLACE_ME
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - ADMIN_EMAIL=admin@localhost
volumes:
  db:
