services:
  serve:
    image: roboteamtwente/rfid-tracker-serve@sha256:b25e65d50b47461d51c552288969cc27ec44a33d9ef1e366bffc8f025a6ba1ce
    ports:
      - 8000:8000
    volumes:
      - db:/db
    environment:
      - DATABASE_URL=sqlite:///db/db.sqlite3
      - DJANGO_DEBUG=False
volumes:
  db:
