services:
  serve:
    image: roboteamtwente/rfid-tracker-serve
    ports:
      - 8001:8000
    volumes:
      - db:/db
    environment:
      - DATABASE_URL=sqlite:///db/db.sqlite3
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - ADMIN_EMAIL=admin@localhost
volumes:
  db:
