services:
  serve:
    image: roboteamtwente/rfid-tracker-serve@sha256:1e474b65e2a9385f8fecfc56998cb7fb0c36e22425d1a6adb9c2a98eaf7bc2f2
    ports:
      - 8000:8000
    volumes:
      - db:/db
    environment:
      - DATABASE_URL=sqlite:///db/db.sqlite3
      - DJANGO_DEBUG=False
volumes:
  db:
