# Generated by Django 5.2.5 on 2025-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0012_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, null=True),
        ),
    ]
