# Generated by Django 5.2.5 on 2025-09-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0013_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
