# Generated by Django 5.2.5 on 2025-09-23 13:55

from django.db import migrations, models

import webui.models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0014_alter_statistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='id',
            field=models.CharField(
                default=webui.models.Scanner.generate_scanner_id,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
