# Generated by Django 5.2.5 on 2025-09-25 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0015_alter_scanner_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
