# Generated by Django 5.2.5 on 2025-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0015_alter_scanner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='starting_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
