# Generated by Django 5.2.5 on 2025-09-25 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0016_alter_membership_starting_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='starting_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
