# Generated by Django 5.2.5 on 2025-09-25 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0016_alter_membership_starting_from'),
        ('webui', '0016_alter_statistics_options'),
    ]

    operations = []
