# Generated by Django 5.2.5 on 2025-09-25 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0017_alter_membership_starting_from'),
        ('webui', '0017_merge_20250925_1314'),
    ]

    operations = []
