# Generated by Django 5.2.5 on 2025-10-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0018_merge_20250925_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='scanner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='logs',
                to='webui.scanner',
            ),
        ),
        migrations.AlterField(
            model_name='log',
            name='tag',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='logs',
                to='webui.tag',
            ),
        ),
        migrations.AlterField(
            model_name='membership',
            name='job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='webui.job',
            ),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subteam',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='members',
                to='webui.subteam',
            ),
        ),
    ]
