name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: read
concurrency:
  group: release
  cancel-in-progress: false
jobs:
  parse-version:
    name: Parse this release's version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - run: |
          version="${GITHUB_REF_NAME#v}"
          # shellcheck disable=SC2129
          echo "patch=$version" >> "$GITHUB_OUTPUT"
          echo "minor=${version%.*}" >> "$GITHUB_OUTPUT"
          echo "major=${version%.*.*}" >> "$GITHUB_OUTPUT"
  upload-dockerhub:
    name: Build & upload the container image to Dockerhub
    runs-on: ubuntu-latest
    needs: parse-version
    steps:
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          username: RoboTeamTwente
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: '{{defaultContext}}:door_tracker'
          push: true
          tags: |
            docker.io/roboteamtwente/rfid-tracker-serve:{{ needs.parse-version.outputs.patch }} \
            docker.io/roboteamtwente/rfid-tracker-serve:{{ needs.parse-version.outputs.minor }} \
            docker.io/roboteamtwente/rfid-tracker-serve:{{ needs.parse-version.outputs.major }} \
            docker.io/roboteamtwente/rfid-tracker-serve:latest
      - run: just upload-image
  release:
    name: Create a Github release
    runs-on: ubuntu-latest
    needs: upload-dockerhub
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0 # get full history
      - uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2
        with:
          tool: git-cliff
      - run: gh release new "${GITHUB_REF_NAME#v}" --notes "$(git cliff --latest --strip all)"
