name: Test
on:
  push:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:debian@sha256:2b3e946e705a41ec8551c1341e00cb850710de8bb8043e643493a95a386dfc78
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: cd door_tracker && uv sync --locked --no-progress
      - run: cd door_tracker && uv run manage.py test --noinput
